FIX Remove pinning pytest-asyncio==0.6.0 on py35 testing
It caused:
ERROR: InvocationError for command '/app/.tox/py35/bin/py.test tests --cov-report=term-missing --cov-report=xml --cov-append --cov=time_execution -v -s' (exited with code 1)

See: https://travis-ci.org/kpn-digital/py-timeexecution/builds/479914752#L907